on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  detect_env:
    runs-on: ubuntu-latest
    outputs:
      environment_name: ${{ steps.set-env.outputs.env-name }}
    steps:
      - uses: actions/checkout@v4
      - id: set-env
        run: |
          # Get list of files changed in this PR
          files=$(git diff --name-only origin/main)
          echo "Changed files: $files"

          # Default environment
          env_name="validation"

          # Loop over files to find folder matching accounts/<env>/vpc/
          for file in $files; do
            if [[ "$file" =~ ^accounts/([^/]+)/vpc/ ]]; then
              env_name="${BASH_REMATCH[1]}"
              break
            fi
          done

          echo "Detected environment: $env_name"
          echo "env-name=$env_name" >> $GITHUB_OUTPUT

  terraform:
    needs: detect_env
    runs-on: ubuntu-latest
    environment: ${{ needs.detect_env.outputs.environment_name }}
    defaults:
      run:
        working-directory: ${{ format('accounts/{0}/vpc', needs.detect_env.outputs.environment_name) }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -out=${{ needs.detect_env.outputs.environment_name }}-plan.tfplan